#!/bin/bash

echo "🚀 StructCrew Website Deployment Guide"
echo "========================================\n"

echo "📋 Domain: structcrew.online"
echo "📁 Website folder: structcrew-website/\n"

echo "Option 1: Deploy to Netlify (Recommended)"
echo "-------------------------------------------"
echo "1. Go to https://app.netlify.com"
echo "2. Drag and drop the 'structcrew-website' folder"
echo "3. In Netlify Dashboard → Domain Settings → Add Custom Domain"
echo "4. Enter: structcrew.online"
echo "5. Also add: www.structcrew.online\n"

echo "DNS Records to Add in Hostinger:"
echo "--------------------------------"
echo "DELETE existing A record for @\n"
echo "ADD these records:"
echo "Type: A"
echo "Name: @"
echo "Points to: [Get IP from Netlify Domain Settings]"
echo "TTL: 3600\n"
echo "Type: CNAME"
echo "Name: www"
echo "Points to: [your-site-name].netlify.app"
echo "TTL: 3600\n"

echo "KEEP these email records (do NOT delete):"
echo "-----------------------------------------"
echo "CNAME brevo1._domainkey → b1.structcrew-online.dkim.brevo.com"
echo "CNAME brevo2._domainkey → b2.structcrew-online.dkim.brevo.com"
echo "TXT _dmarc → v=DMARC1; p=none; rua=mailto:rua@dmarc.brevo.com"
echo "TXT brevo-code → 680f353f2fe75c0144df3777b4f6e518\n"

echo "Option 2: Deploy to Vercel (Alternative)"
echo "-----------------------------------------"
echo "Run these commands:"
echo "  cd structcrew-website"
echo "  npm install -g vercel"
echo "  vercel\n"
echo "Then in Vercel Dashboard:"
echo "1. Settings → Domains → Add structcrew.online"
echo "2. Follow the DNS instructions provided by Vercel\n"

echo "DNS Records for Vercel:"
echo "----------------------"
echo "Type: CNAME"
echo "Name: @"
echo "Points to: cname.vercel-dns.com"
echo "TTL: 3600\n"
echo "Type: CNAME"
echo "Name: www"
echo "Points to: cname.vercel-dns.com"
echo "TTL: 3600\n"

echo "⚠️  IMPORTANT:"
echo "=============="
echo "1. Delete old A record pointing to 84.32.84.32"
echo "2. Keep all email-related DNS records (Brevo)"
echo "3. DNS changes can take 5-30 minutes to propagate"
echo "4. Test with: curl -I http://structcrew.online\n"

echo "✅ After deployment, your site will be available at:"
echo "   https://structcrew.online"
echo "   https://www.structcrew.online\n"

echo "📚 For detailed guide, see: structcrew-website/README.md"
echo "🔧 For DNS issues, check: DOMAIN_SETUP_GUIDE.md"